export enum EquipType {
    OPTICAL_SIGHT = 1,
    HOLOGRAPHIC_SIGHT,
    RED_DOT_SIGHT,
    NIGHT_BATTLE_EQUIPMENT,
    ARMOR_PIERCING_AMMO,
    HOLLOW_POINT_AMMO,
    SHOTGUN_SHELL,
    HIGH_VELOCITY_AMMO,
    MICROCHIP,
    EXOSKELETON,
    ARMOR_PLATE,
    SPECIAL_TDOLL,
    SUPPRESSOR,
    AMMO_BOX,
    CAMOUFLAGE_CAPE,
    SPECIAL_ACCESSORY,
    SPECIAL_MAGAZINE
}
